name: Check and package
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - run: ./scripts/test.sh
      - run: docker build -t whisper-test ./whisper-service
      - run: docker run --rm -v "$PWD/tests:/tests:ro" whisper-test python /tests/test_speech.py
      - run: python3 scripts/package.py
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: Whisper-plugin
          path: dist/Whisper-*.zip*
